@startuml
' declate title
title 6.1.3. getSettlementWindowByParams GET: /settlementWindows

autonumber

' Actor Keys:
' declare actors

actor "Hub Employee" as OPERATOR

boundary "Settlement Service API" as SSAPI
control "Settlement Window" as SETTLEWINDOW
entity "Settlement DAO" as SETTLE_DAO

database "Central Store" as DB

box "Central HUB" #LightPink
    participant OPERATOR
end box

box "Settlement Service" #LightGreen
    participant SSAPI
    participant SETTLEWINDOW
    participant SETTLE_DAO
end box

box "Central Services" #LightYellow
    participant DB
end box

' start flow

group Request Settlement Window properties
    activate OPERATOR
    note right of OPERATOR #Yellow
        state={state}
        &fromDateTime={dateTime}
        &toDateTime={dateTime}
        &participantId={id}
    end note
    OPERATOR -> SSAPI: GET - /settlementWindows/{id}
    deactivate OPERATOR
    activate SSAPI
    SSAPI -> SETTLEWINDOW: Request settlementWindow
    deactivate SSAPI
    activate SETTLEWINDOW
    SETTLEWINDOW -> SETTLE_DAO: Request settlementWindow
    activate SETTLE_DAO
    SETTLE_DAO -> DB: Fetch settlementWindow as specified \n<color #FF0000><b>Error code:</b> 2001</color>
    activate DB
    hnote over DB #LightYellow
        settlementWindow
        settlementWindowStateChange
        transferFulfilment
        transfer
        transferParticipant
        participantCurrency
        settlementParticipantCurrency
        settlementParticipantCurrencyStateChange
    end hnote
    note over DB #LightGray
        Indication of tables to query for variables to be returned

        (state) {all if no parameter}
        settlementWindow
        settlementWindowStateChange - description from settlementWindowState

        (participantId) {all if no parameter)
        transferFulfilment
        transfer
        transferParticipant
        participantCurrency

        (netAmount)
        settlementParticipantCurrency

        (settlementState)
        settlementParticipantCurrencyStateChange - description for settlementState
        (reason)
        (createDate)
        settlementParticipantCurrencyStateChange

    end note
    SETTLE_DAO <-- DB: Return settlementWindow with parameter
    deactivate DB
    alt Return settlementWindow(s) as per parameters
        SETTLEWINDOW <- SETTLE_DAO: Successful - settlementWindow(s) found
        SSAPI <- SETTLEWINDOW: Operation successfully completed
        deactivate SETTLEWINDOW
        activate SSAPI
        note left of SSAPI #Yellow
          {
            "Id": 0,
            "State": "string",
            "settlementWindows": [
              [
                {
                  "id": 0,
                  "reason": "string",
                  "state": "string",
                  "createdDate": "string",
                  "changedDate": "string"
                }
              ]
            ],
            "Participants": [
              {
                "id": 0,
                "accounts": [
                  {
                    "id": "string",
                    "reason": "string",
                    "state": "PENDING-SETTLEMENT",
                    "netSettlementAmount": {
                      "amount": 0,
                      "currency": "string"
                    }
                  }
                ]
              }
            ]
          }
        end note
        OPERATOR <- SSAPI: Return results
        deactivate SSAPI
    else <color #FF0000><b>Settlement Window not found</b></color>
        SETTLE_DAO -> SSAPI: settlement window not found - Return ERROR
        deactivate SETTLE_DAO
        activate SSAPI
        SSAPI -> SSAPI: Update Event log
        note right of SSAPI #LightBlue
            Log ERROR Messages.
            Update Event log with ERROR.
        end note
        note left of SSAPI #Yellow
            {
              "status": 0,
              "code": "(ERROR response code eg. '404' - Defined in swagger definition))",
              "message": "string"
            }
        end note
        OPERATOR <- SSAPI: Return ERROR
        deactivate SSAPI
    end
end
@enduml
