@startuml
' declate title
title Returns a Settlement Window as per id
'title 6.1.1. getSettlementWindowById GET: /settlementWindows

autonumber

' declare actors
actor "Hub Employee" as OPERATOR

boundary "Settlement Service API" as SSAPI
entity "Settlement DAO" as SETTLE_DAO

database "Central Store" as DB

box "Central HUB" #LightPink
    participant OPERATOR
end box

box "Settlement Service" #LightGreen
    participant SSAPI
    participant SETTLE_DAO
end box

box "Central Services" #LightYellow
    participant DB
end box

' start flow
group Request Settlement Window properties
    activate OPERATOR
    OPERATOR -> SSAPI: GET - /settlementWindows/{id}
    activate SSAPI
    SSAPI -> SETTLE_DAO: Request settlementWindow
    activate SETTLE_DAO
    SETTLE_DAO -> DB: Request settlementWindow\n<color #FF0000><b>Error code:</b> 2001</color>
    activate DB
    hnote over DB #LightYellow
        **settlementWindow**
            createDate
        **settlementWindowStateChange**
            state
            reason
            changeDate
'        SELECT MAX(settlementWindowStateId) as currentstate
'        FROM **settlementWindowStateChange**
'        WHERE (settlementWindowId = {id})
'        GROUP BY settlementWindowStateId

'        SELECT settlementWindowId, settlementWindowStateId, reason, createDate
'        FROM **settlementWindowStateChange**
'        WHERE (settlementWindowStateId = {currentstate});
    end hnote
    SETTLE_DAO <-- DB: Return results
    deactivate DB
    alt settlementWindow found
        SSAPI <-- SETTLE_DAO: Operation successfully completed
        note left of SSAPI #Yellow
            {
              "id": 0,
              "reason": "string",
              "state": "string",
              "createdDate": "string",
              "changedDate": "string"
            }
        end note
        OPERATOR <-- SSAPI: Return results
    else <color #FF0000><b>Settlement Window not found</b></color>
        SETTLE_DAO --> SSAPI: settlement window not found - Return ERROR
        deactivate SETTLE_DAO
        SSAPI --> SSAPI: Update Event log
        note right of SSAPI #LightBlue
            Log ERROR Messages.
            Update Event log with ERROR.
        end note
        note left of SSAPI #Yellow
            {
              "status": 0,
              "code": "(ERROR response code eg. '404' - Defined in swagger definition))",
              "message": "string"
            }
        end note
        OPERATOR <-- SSAPI: Return ERROR
    deactivate SSAPI
    deactivate OPERATOR
    end
end
@enduml
