@startuml
' declate title
title 6.1.1. getSettlementWindowById GET: /settlementWindows

autonumber

' Actor Keys:

' declare actors

actor "Hub Employee" as OPERATOR

boundary "Settlement Service API" as SSAPI
control "Settlement Window" as SETTLEWINDOW
entity "Settlement DAO" as SETTLE_DAO

database "Central Store" as DB

box "Central HUB" #LightPink
    participant OPERATOR
end box

box "Settlement Service" #LightGreen
    participant SSAPI
    participant SETTLEWINDOW
    participant SETTLE_DAO
end box

box "Central Services" #LightYellow
    participant DB
end box

' start flow

group Request Settlement Window properties
    note right of OPERATOR #Yellow
        GET:: '/settlementWindows/{id}'
    end note
    OPERATOR -> SSAPI: API call Settlement Service to get settlement window detail
    activate SSAPI
    SSAPI -> SETTLEWINDOW: Get settlement window
    deactivate SSAPI
    activate SETTLEWINDOW
    alt
        SETTLEWINDOW -> SETTLE_DAO: Get settlementWindow<id> properties
        activate SETTLE_DAO
                SETTLE_DAO -> DB: Get settlementWindow< properties from DB \n<color #FF0000><b>Error code:</b> 2001</color>
            activate DB
                hnote over DB #LightYellow
                settlementWindow
                settlementWindowStateChange
                end hnote
                SETTLE_DAO <- DB: Return properties for settlementWindow<id>
            deactivate DB
        SETTLEWINDOW <- SETTLE_DAO: Successful - settlementWindow found
        SSAPI <- SETTLEWINDOW: Operation successfully completed
        deactivate SETTLEWINDOW
        activate SSAPI
        OPERATOR <- SSAPI: Return results
        note left of SSAPI #Yellow
            {
              "id": 0,
              "reason": "string",
              "state": "string",
              "createdDate": "string",
              "changedDate": "string"
            }
        end note
        deactivate SSAPI
    else <color #FF0000><b>Settlement Window not found</b></color>
        SETTLE_DAO -> SSAPI: settlement window not found - Return ERROR
        deactivate SETTLE_DAO
        activate SSAPI
        SSAPI -> SSAPI: Update Event log
        note right of SSAPI #LightBlue
            Log ERROR Messages.
            Update Event log with ERROR.
        end note
        OPERATOR <- SSAPI: Return ERROR
        deactivate SSAPI
        note left of SSAPI #Yellow
            {
              "status": 0,
              "code": "MISSING_REQUIRED_PARAMETER",
              "message": "string"
            }
        end note
    end
end
@enduml