@startuml
' declate title
title 6.1.1. Creation of Settlement Event

autonumber

' Actor Keys:

' declare actors

actor "Hub Operations" as OPERATOR

boundary "Settlement Service API" as SSAPI
'control "Settlements" as SETTLEMENT
control "Settlement Window" as SETTLEWINDOW

boundary "Central Service API" as CSAPI
'entity "Participant DAO" as PARTICIPANT_DAO
database "Central Store" as DB

box "Central Bank" #LightPink
    participant OPERATOR
end box

box "Settlement Service" #LightGreen
    participant SSAPI
    participant SETTLEWINDOW
'    participant SETTLEMENT
end box

box "Central Services" #LightYellow
    participant CSAPI
'    participant PARTICIPANT_DAO
    participant DB
end box

' start flow
activate SETTLEWINDOW

group Settlement Trigger received from "HUB"
    OPERATOR -> SETTLEWINDOW: Settlement event trigger
    SETTLEWINDOW -> DB: Get open settlementWindow
    group Validation Event
        SETTLEWINDOW -> DB: Check for Settlement Windows that is open\n Rule: state: 'open'
    end
    note right of SETTLEWINDOW #lightblue
        Processing within DB Transaction
        Check settlementWindow status 'closed' 'open'
        Check that all settlement windows are not allocated
        Check settlements in settlement window - updates to DB
        Check for settlement windows that can be 'closed'
    end note
    note right of SETTLEWINDOW #lightblue
        SettlementWindos ERRORS
        Check settlementWindow status != 'closed' || 'open'
        Check settlementWindow status == 'open' not allocated

    end note


deactivate SETTLEWINDOW
@enduml