@startuml
' declate title
title 6.1.1. Creation of Settlement Event

autonumber

' Actor Keys:

' declare actors

actor "Hub Operations" as OPERATOR

boundary "Settlement Service API" as SSAPI
control "Settlements" as SETTLEMENT
control "Settlement Window" as SETTLEWINDOW

boundary "Central Service API" as CSAPI
entity "Participant DAO" as PARTICIPANT_DAO
database "Central Store" as DB

box "Central Bank" #LightPink
    participant OPERATOR
end box

box "Settlement Service" #LightGreen
    participant SSAPI
    participant SETTLEWINDOW
    participant SETTLEMENT
end box

box "Central Services" #LightYellow
    participant CSAPI
    participant PARTICIPANT_DAO
    participant DB
end box

' start flow
activate SETTLEMENT

group Settlement Trigger received from "HUB"
    OPERATOR -> SETTLEMENT: Settlement event trigger
    ref over SETTLEWINDOW, DB
    SETTLEMENT <--> DB: Get open settlementWindow as per {6.1.2}.
    end

    group Event
        SETTLEMENT <--> DB: Assign Settlement to settlementWindow Rule: ???
        group Validate
            SETTLEMENT <--> DB: Assign Settlement are not already asigned to settlementWindow
        end
    end

    group Process settlementWindow and associations
    SETTLEWINDOW <--> SETTLEMENT: - Allocate settlement to settlementWindows
    end
    note right of SETTLEMENT #lightblue
        Create settlement in settlementWindow

        Cross reference for associated settlementWindows
        Calculate the net settlement amount for all participants with pending transfers(settlements) in settlementWindow

        Return dataset - the net settlements for the settlementWindow
    end note
    note right of SETTLEMENT #lightblue
        Create settlement in settlementWindow ERROR

        settlementWindows already in process - not 'closed'
        no settlement for the settlementWindow
        'failed' settlements
    end note

end
deactivate SETTLEMENT
@enduml